# Generated by Django 2.2.5 on 2020-07-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField(default=18)),
                ('email', models.EmailField(max_length=30)),
                ('age', models.IntegerField(default=18)),
                ('instahandle', models.CharField(default='not provided', max_length=50)),
                ('collegename', models.CharField(max_length=50)),
                ('placeofstudy', models.CharField(default='HYD', max_length=50)),
                ('year_class', models.IntegerField()),
                ('Field_of_study', models.CharField(max_length=50)),
                ('Hobbies', models.CharField(max_length=50)),
                ('password', models.CharField(default='no stored', max_length=50)),
            ],
        ),
    ]
