# Generated by Django 2.2.5 on 2020-07-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartapp', '0002_auto_20200713_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketerdetail',
            name='district',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marketerdetail',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marketerdetail',
            name='sub_colony',
            field=models.CharField(max_length=30),
        ),
    ]
