# Generated by Django 2.2.5 on 2020-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartapp', '0003_auto_20200713_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketerdetail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
