# Generated by Django 2.2.5 on 2020-07-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartapp', '0004_marketerdetail_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketerdetail',
            name='address',
            field=models.CharField(default='notgiven', max_length=256),
        ),
        migrations.AlterField(
            model_name='marketerdetail',
            name='Type_of_community',
            field=models.CharField(choices=[('apartment', 'Apartments'), ('villa', 'Villas'), ('colony', 'Colony'), ('Gated_community', 'Gated community')], default='apartment', max_length=20),
        ),
    ]
