# Generated by Django 2.2.5 on 2020-07-29 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartapp', '0007_auto_20200729_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketerdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
