# Generated by Django 2.2.5 on 2020-07-29 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartapp', '0008_auto_20200729_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketerdetail',
            name='user',
        ),
        migrations.AlterField(
            model_name='marketerdetail',
            name='Type_of_community',
            field=models.CharField(choices=[('apartment', 'Apartments'), ('villa', 'Villas'), ('colony', 'Colony'), ('Gated_community', 'Gated community')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketerdetail',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
