# Generated by Django 2.2.18 on 2021-02-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartapp', '0009_auto_20200729_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketerdetail',
            name='credits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
