# Generated by Django 2.2.18 on 2021-02-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartapp', '0010_marketerdetail_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketerdetail',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
