# Generated by Django 2.2.18 on 2021-02-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartapp', '0014_auto_20210207_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketerdetail',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
