# Generated by Django 3.1.7 on 2021-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartapp', '0015_auto_20210208_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketerdetail',
            name='adhaarnumber',
        ),
        migrations.RemoveField(
            model_name='marketerdetail',
            name='currentbill',
        ),
        migrations.RemoveField(
            model_name='marketerdetail',
            name='no_of_blocks',
        ),
        migrations.RemoveField(
            model_name='marketerdetail',
            name='no_of_flats_or_houses',
        ),
        migrations.RemoveField(
            model_name='marketerdetail',
            name='partner',
        ),
        migrations.AddField(
            model_name='marketerdetail',
            name='instagramlink',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='marketerdetail',
            name='Type_of_community',
            field=models.CharField(choices=[('skillbattleartist', 'Skillbattle artist'), ('gabblecastpodcaster', 'Gabblecast podcaster'), ('skillbattleambassador', 'Skillbattle ambassador'), ('gabblecast_ambassador', 'Gabblecast ambassador'), ('skillbattleabroadartist', 'Skillbattle abroad artist'), ('gabblecastabroadpodcaster', 'Gabblecast abroad podcaster')], max_length=25),
        ),
    ]
