# Generated by Django 2.2.5 on 2020-07-12 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
