# Generated by Django 2.2.5 on 2020-07-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200712_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatnumber', models.IntegerField()),
                ('apartmentaddress', models.CharField(max_length=50)),
                ('productname', models.CharField(max_length=32)),
                ('dealername', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='product_details',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='marketer',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
    ]
