# Generated by Django 2.2.5 on 2020-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200713_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='sample_price',
            field=models.IntegerField(default=0),
        ),
    ]
