# Generated by Django 2.2.5 on 2020-07-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200713_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_price',
            field=models.IntegerField(),
        ),
    ]
