# Generated by Django 2.2.5 on 2020-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200713_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available_region',
            field=models.CharField(default='not available', max_length=120),
        ),
    ]
