# Generated by Django 2.2.5 on 2020-07-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_available_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='flatnumber',
            new_name='flataddress',
        ),
    ]
