# Generated by Django 2.2.5 on 2020-07-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200713_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='flataddress',
            field=models.CharField(default='Not provided', max_length=50),
        ),
    ]
