# Generated by Django 2.2.5 on 2020-07-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_orders_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='buyername',
            field=models.CharField(default='not given', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
