# Generated by Django 2.2.5 on 2020-07-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200725_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phonenumber',
            field=models.CharField(default='not given', max_length=20),
        ),
    ]
