# Generated by Django 2.2.5 on 2020-07-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_marketer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='available_region',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='marketer_phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
