# Generated by Django 2.2.5 on 2020-07-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200725_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_link',
            field=models.CharField(default='no link', max_length=256),
        ),
    ]
