# Generated by Django 2.2.5 on 2020-07-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available_in',
            field=models.CharField(choices=[('all', 'All'), ('apartment', 'Apartments'), ('villa', 'Villas'), ('colony', 'Colony'), ('Gated_community', 'Gated community')], default='all', max_length=20),
        ),
    ]
