# Generated by Django 2.2.5 on 2020-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_available_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.URLField(default='https://www.youtube.com/embed/-9fMvHicwLE', max_length=256),
        ),
    ]
