# Generated by Django 2.2.5 on 2020-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_link',
            field=models.URLField(default='https://www.youtube.com/embed/hoNb6HuNmU0', max_length=256),
        ),
    ]
