# Generated by Django 2.2.5 on 2020-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200811_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_link',
            field=models.URLField(default='https://www.youtube.com/embed/vGHrJDmepI0', max_length=256),
        ),
    ]
