# Generated by Django 2.2.5 on 2020-08-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200811_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_link',
            field=models.CharField(default='<iframe width="560" height="315" src="https://www.youtube.com/embed/M-O0uCYCBNk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>', max_length=256),
        ),
    ]
