# Generated by Django 2.2.5 on 2020-08-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200811_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_link',
            field=models.CharField(default='you', max_length=256),
        ),
    ]
