# Generated by Django 2.2.18 on 2021-02-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_filesload_participate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesLoad',
        ),
        migrations.DeleteModel(
            name='Participate',
        ),
    ]
