# Generated by Django 2.2.18 on 2021-02-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_delete_participate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesLoad',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='completed',
        ),
    ]
