# Generated by Django 2.2.18 on 2021-02-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210213_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earncredits',
            name='author',
            field=models.CharField(max_length=256),
        ),
    ]
