# Generated by Django 3.1.7 on 2021-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210213_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='available_in',
            field=models.CharField(choices=[('all', 'All'), ('skillbattleartist', 'Skillbattle artist'), ('gabblecastpodcaster', 'Gabblecast podcaster'), ('skillbattleambassador', 'Skillbattle ambassador'), ('gabblecast_ambassador', 'Gabblecast ambassador'), ('skillbattleabroadartist', 'Skillbattle abroad artist'), ('gabblecastabroadpodcaster', 'Gabblecast abroad podcaster')], default='all', max_length=25),
        ),
    ]
